# Generated by Django 4.2 on 2026-01-28 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('health', 'Health & Fitness'), ('productivity', 'Productivity'), ('learning', 'Learning'), ('mindfulness', 'Mindfulness'), ('social', 'Social'), ('finance', 'Finance'), ('other', 'Other')], default='other', max_length=50)),
                ('frequency_per_week', models.IntegerField(choices=[(1, 'Once a week'), (2, 'Twice a week'), (3, 'Three times a week'), (4, 'Four times a week'), (5, 'Five times a week'), (6, 'Six times a week'), (7, 'Every day')], default=7)),
                ('motivation_score', models.IntegerField(default=5, help_text='Scale 1-10')),
                ('difficulty_level', models.IntegerField(default=5, help_text='Scale 1-10')),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('total_completions', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Habit',
                'verbose_name_plural': 'Habits',
                'db_table': 'habits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HabitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='habits.habit')),
            ],
            options={
                'verbose_name': 'Habit Record',
                'verbose_name_plural': 'Habit Records',
                'db_table': 'habit_records',
                'ordering': ['-date'],
                'unique_together': {('habit', 'date')},
            },
        ),
    ]
